unstable_features = true
combine_control_expr = false
control_brace_style = "AlwaysNextLine"
brace_style = "AlwaysNextLine"
fn_single_line = true
imports_indent = "Block"
imports_layout = "HorizontalVertical"
reorder_imported_names = true
reorder_imports = true
reorder_imports_in_group = true
trailing_semicolon = false
blank_lines_upper_bound = 2
error_on_line_overflow = false
max_width = 95
