[package]
name = "midscript"
version = "0.1.0"
authors = ["***Realname*** ***Lastname*** <***redacted.email@redacted.nope***>"]

[dependencies]
regex = "~0.2.5"
structopt = "~0.1.6"
structopt-derive = "~0.1.6"

[dev-dependencies]
pretty_assertions = "~0.4.1"

